application: jobstoavoid
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html

- url: /jobs
  script: jobslist.app

- url: /job
  script: jobdesc.app

- url: /
  static_dir: www
